<?php
/**
 * ManageRuleConfigurationputPayloadTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  pmc_102
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Program Administration API
 *
 * The Transaction Controls Program Administration API enables Issuers to change program configurations for their sponsorID.
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace pmc_102\modeltest;

/**
 * ManageRuleConfigurationputPayloadTest Class Doc Comment
 *
 * @category    Class */
// * @description request
/**
 * @package     pmc_102
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ManageRuleConfigurationputPayloadTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ManageRuleConfigurationputPayload"
     */
    public function testManageRuleConfigurationputPayload()
    {

    }

    /**
     * Test attribute "rule_categories"
     */
    public function testPropertyRuleCategories()
    {

    }

    /**
     * Test attribute "card_enrollment_callback_settings"
     */
    public function testPropertyCardEnrollmentCallbackSettings()
    {

    }

    /**
     * Test attribute "is_spend_limit_allowed"
     */
    public function testPropertyIsSpendLimitAllowed()
    {

    }

    /**
     * Test attribute "is_filter_by_country_allowed"
     */
    public function testPropertyIsFilterByCountryAllowed()
    {

    }

}


/**
* --------------------------------------------------------------------------------
*
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
* --------------------------------------------------------------------------------
*/