<?php
/**
 * ManageRuleConfigurationputPayload
 *
 * PHP version 5
 *
 * @category Class
 * @package  pmc_102
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Program Administration API
 *
 * The Transaction Controls Program Administration API enables Issuers to change program configurations for their sponsorID.
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace pmc_102\model;

use \ArrayAccess;

/**
 * ManageRuleConfigurationputPayload Class Doc Comment
 *
 * @category    Class
 * @description request
 * @package     pmc_102
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ManageRuleConfigurationputPayload implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'manageRuleConfigurationputPayload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'rule_categories' => 'string',
        'card_enrollment_callback_settings' => '\pmc_102\model\CardEnrollmentCallbackSettings',
        'is_spend_limit_allowed' => 'bool',
        'is_filter_by_country_allowed' => 'bool'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'rule_categories' => 'ruleCategories',
        'card_enrollment_callback_settings' => 'cardEnrollmentCallbackSettings',
        'is_spend_limit_allowed' => 'isSpendLimitAllowed',
        'is_filter_by_country_allowed' => 'isFilterByCountryAllowed'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'rule_categories' => 'setRuleCategories',
        'card_enrollment_callback_settings' => 'setCardEnrollmentCallbackSettings',
        'is_spend_limit_allowed' => 'setIsSpendLimitAllowed',
        'is_filter_by_country_allowed' => 'setIsFilterByCountryAllowed'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'rule_categories' => 'getRuleCategories',
        'card_enrollment_callback_settings' => 'getCardEnrollmentCallbackSettings',
        'is_spend_limit_allowed' => 'getIsSpendLimitAllowed',
        'is_filter_by_country_allowed' => 'getIsFilterByCountryAllowed'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['rule_categories'] = isset($data['rule_categories']) ? $data['rule_categories'] : null;
        $this->container['card_enrollment_callback_settings'] = isset($data['card_enrollment_callback_settings']) ? $data['card_enrollment_callback_settings'] : null;
        $this->container['is_spend_limit_allowed'] = isset($data['is_spend_limit_allowed']) ? $data['is_spend_limit_allowed'] : null;
        $this->container['is_filter_by_country_allowed'] = isset($data['is_filter_by_country_allowed']) ? $data['is_filter_by_country_allowed'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['rule_categories'] === null) {
            $invalid_properties[] = "'rule_categories' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['rule_categories'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets rule_categories
     * @return string
     */
    public function getRuleCategories()
    {
        return $this->container['rule_categories'];
    }

    /**
     * Sets rule_categories
     * @param string $rule_categories Allowed Rule categories configured for this Sponsor ID
     * @return $this
     */
    public function setRuleCategories($rule_categories)
    {
        $this->container['rule_categories'] = $rule_categories;

        return $this;
    }

    /**
     * Gets card_enrollment_callback_settings
     * @return \pmc_102\model\CardEnrollmentCallbackSettings
     */
    public function getCardEnrollmentCallbackSettings()
    {
        return $this->container['card_enrollment_callback_settings'];
    }

    /**
     * Sets card_enrollment_callback_settings
     * @param \pmc_102\model\CardEnrollmentCallbackSettings $card_enrollment_callback_settings
     * @return $this
     */
    public function setCardEnrollmentCallbackSettings($card_enrollment_callback_settings)
    {
        $this->container['card_enrollment_callback_settings'] = $card_enrollment_callback_settings;

        return $this;
    }

    /**
     * Gets is_spend_limit_allowed
     * @return bool
     */
    public function getIsSpendLimitAllowed()
    {
        return $this->container['is_spend_limit_allowed'];
    }

    /**
     * Sets is_spend_limit_allowed
     * @param bool $is_spend_limit_allowed isSpendLimitAllowed is dependent on the sponsor whether it allows setting up spend limit control or not
     * @return $this
     */
    public function setIsSpendLimitAllowed($is_spend_limit_allowed)
    {
        $this->container['is_spend_limit_allowed'] = $is_spend_limit_allowed;

        return $this;
    }

    /**
     * Gets is_filter_by_country_allowed
     * @return bool
     */
    public function getIsFilterByCountryAllowed()
    {
        return $this->container['is_filter_by_country_allowed'];
    }

    /**
     * Sets is_filter_by_country_allowed
     * @param bool $is_filter_by_country_allowed isFilterByCountryAllowed is dependent on the sponsor whether it allows setting up country enable or disabled list
     * @return $this
     */
    public function setIsFilterByCountryAllowed($is_filter_by_country_allowed)
    {
        $this->container['is_filter_by_country_allowed'] = $is_filter_by_country_allowed;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\pmc_102\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\pmc_102\ObjectSerializer::sanitizeForSerialization($this));
    }
}

/**
* ----------------------------------------------------------------------------------------------------------------------
*
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
* ----------------------------------------------------------------------------------------------------------------------
*/