<?php
/**
 * ImmediateLoad
 *
 * PHP version 5
 *
 * @category Class
 * @package  dcas_101
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Card Services API
 *
 * Manage cardholder’s card and account information, notification settings, and balance information.
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace dcas_101\model;

use \ArrayAccess;

/**
 * ImmediateLoad Class Doc Comment
 *
 * @category    Class
 * @description Request to perform an immediate load.
 * @package     dcas_101
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ImmediateLoad implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'immediateLoad';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'fee_number' => 'string',
        'load_amount' => '\dcas_101\model\LoadAmount',
        'fee_amount' => '\dcas_101\model\FeeAmount',
        'funding_account_alias_id' => 'string',
        'cvv2' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'fee_number' => 'feeNumber',
        'load_amount' => 'loadAmount',
        'fee_amount' => 'feeAmount',
        'funding_account_alias_id' => 'fundingAccountAliasId',
        'cvv2' => 'cvv2'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'fee_number' => 'setFeeNumber',
        'load_amount' => 'setLoadAmount',
        'fee_amount' => 'setFeeAmount',
        'funding_account_alias_id' => 'setFundingAccountAliasId',
        'cvv2' => 'setCvv2'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'fee_number' => 'getFeeNumber',
        'load_amount' => 'getLoadAmount',
        'fee_amount' => 'getFeeAmount',
        'funding_account_alias_id' => 'getFundingAccountAliasId',
        'cvv2' => 'getCvv2'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['fee_number'] = isset($data['fee_number']) ? $data['fee_number'] : null;
        $this->container['load_amount'] = isset($data['load_amount']) ? $data['load_amount'] : null;
        $this->container['fee_amount'] = isset($data['fee_amount']) ? $data['fee_amount'] : null;
        $this->container['funding_account_alias_id'] = isset($data['funding_account_alias_id']) ? $data['funding_account_alias_id'] : null;
        $this->container['cvv2'] = isset($data['cvv2']) ? $data['cvv2'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['fee_number'] === null) {
            $invalid_properties[] = "'fee_number' can't be null";
        }
        if ($this->container['load_amount'] === null) {
            $invalid_properties[] = "'load_amount' can't be null";
        }
        if ($this->container['fee_amount'] === null) {
            $invalid_properties[] = "'fee_amount' can't be null";
        }
        if ($this->container['funding_account_alias_id'] === null) {
            $invalid_properties[] = "'funding_account_alias_id' can't be null";
        }
        if ($this->container['cvv2'] === null) {
            $invalid_properties[] = "'cvv2' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['fee_number'] === null) {
            return false;
        }
        if ($this->container['load_amount'] === null) {
            return false;
        }
        if ($this->container['fee_amount'] === null) {
            return false;
        }
        if ($this->container['funding_account_alias_id'] === null) {
            return false;
        }
        if ($this->container['cvv2'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets fee_number
     * @return string
     */
    public function getFeeNumber()
    {
        return $this->container['fee_number'];
    }

    /**
     * Sets fee_number
     * @param string $fee_number The fee number associated with the fee amount.
     * @return $this
     */
    public function setFeeNumber($fee_number)
    {
        $this->container['fee_number'] = $fee_number;

        return $this;
    }

    /**
     * Gets load_amount
     * @return \dcas_101\model\LoadAmount
     */
    public function getLoadAmount()
    {
        return $this->container['load_amount'];
    }

    /**
     * Sets load_amount
     * @param \dcas_101\model\LoadAmount $load_amount
     * @return $this
     */
    public function setLoadAmount($load_amount)
    {
        $this->container['load_amount'] = $load_amount;

        return $this;
    }

    /**
     * Gets fee_amount
     * @return \dcas_101\model\FeeAmount
     */
    public function getFeeAmount()
    {
        return $this->container['fee_amount'];
    }

    /**
     * Sets fee_amount
     * @param \dcas_101\model\FeeAmount $fee_amount
     * @return $this
     */
    public function setFeeAmount($fee_amount)
    {
        $this->container['fee_amount'] = $fee_amount;

        return $this;
    }

    /**
     * Gets funding_account_alias_id
     * @return string
     */
    public function getFundingAccountAliasId()
    {
        return $this->container['funding_account_alias_id'];
    }

    /**
     * Sets funding_account_alias_id
     * @param string $funding_account_alias_id The funding account alias identifier.
     * @return $this
     */
    public function setFundingAccountAliasId($funding_account_alias_id)
    {
        $this->container['funding_account_alias_id'] = $funding_account_alias_id;

        return $this;
    }

    /**
     * Gets cvv2
     * @return string
     */
    public function getCvv2()
    {
        return $this->container['cvv2'];
    }

    /**
     * Sets cvv2
     * @param string $cvv2 The cardholder cvv2 value.
     * @return $this
     */
    public function setCvv2($cvv2)
    {
        $this->container['cvv2'] = $cvv2;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\dcas_101\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\dcas_101\ObjectSerializer::sanitizeForSerialization($this));
    }
}

/**
* ----------------------------------------------------------------------------------------------------------------------
*
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
* ----------------------------------------------------------------------------------------------------------------------
*/