<?php
/**
 * EditCompanyputResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  vba_102
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Company API
 *
 * The VISA B2B Connect REST API allows developers to perform operations from a company or bank perspective.  The VISA B2B Connect API allows you to create and update profiles or retreive information that is relevant to you.
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace vba_102\modeltest;

/**
 * EditCompanyputResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description Successful request
/**
 * @package     vba_102
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EditCompanyputResponseTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "EditCompanyputResponse"
     */
    public function testEditCompanyputResponse()
    {

    }

    /**
     * Test attribute "company_profile"
     */
    public function testPropertyCompanyProfile()
    {

    }

    /**
     * Test attribute "company_id"
     */
    public function testPropertyCompanyId()
    {

    }

    /**
     * Test attribute "status_text"
     */
    public function testPropertyStatusText()
    {

    }

    /**
     * Test attribute "last_updated"
     */
    public function testPropertyLastUpdated()
    {

    }

    /**
     * Test attribute "blocked_corridors"
     */
    public function testPropertyBlockedCorridors()
    {

    }

    /**
     * Test attribute "bank_id"
     */
    public function testPropertyBankId()
    {

    }

    /**
     * Test attribute "transaction_limits"
     */
    public function testPropertyTransactionLimits()
    {

    }

}


/**
* --------------------------------------------------------------------------------
*
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
* --------------------------------------------------------------------------------
*/