<?php
/**
 * GetpaymentDetailspostResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  vpa_102
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Payment Service
 *
 * The Payment web service is used for processing payments and sending payment remittance information to the appropriate suppliers.
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace vpa_102\model;

use \ArrayAccess;

/**
 * GetpaymentDetailspostResponse Class Doc Comment
 *
 * @category    Class
 * @description OK
 * @package     vpa_102
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetpaymentDetailspostResponse implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'getpaymentDetailspostResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'has_more_elements' => 'string',
        'result_set_no' => 'string',
        'total_record_count' => 'string',
        'payments' => '\vpa_102\model\Payments',
        'message_id' => 'string',
        'status_desc' => 'string',
        'status_code' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'has_more_elements' => 'hasMoreElements',
        'result_set_no' => 'resultSetNo',
        'total_record_count' => 'totalRecordCount',
        'payments' => 'payments',
        'message_id' => 'messageId',
        'status_desc' => 'statusDesc',
        'status_code' => 'statusCode'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'has_more_elements' => 'setHasMoreElements',
        'result_set_no' => 'setResultSetNo',
        'total_record_count' => 'setTotalRecordCount',
        'payments' => 'setPayments',
        'message_id' => 'setMessageId',
        'status_desc' => 'setStatusDesc',
        'status_code' => 'setStatusCode'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'has_more_elements' => 'getHasMoreElements',
        'result_set_no' => 'getResultSetNo',
        'total_record_count' => 'getTotalRecordCount',
        'payments' => 'getPayments',
        'message_id' => 'getMessageId',
        'status_desc' => 'getStatusDesc',
        'status_code' => 'getStatusCode'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['has_more_elements'] = isset($data['has_more_elements']) ? $data['has_more_elements'] : null;
        $this->container['result_set_no'] = isset($data['result_set_no']) ? $data['result_set_no'] : null;
        $this->container['total_record_count'] = isset($data['total_record_count']) ? $data['total_record_count'] : null;
        $this->container['payments'] = isset($data['payments']) ? $data['payments'] : null;
        $this->container['message_id'] = isset($data['message_id']) ? $data['message_id'] : null;
        $this->container['status_desc'] = isset($data['status_desc']) ? $data['status_desc'] : null;
        $this->container['status_code'] = isset($data['status_code']) ? $data['status_code'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['has_more_elements'] === null) {
            $invalid_properties[] = "'has_more_elements' can't be null";
        }
        if ($this->container['result_set_no'] === null) {
            $invalid_properties[] = "'result_set_no' can't be null";
        }
        if ($this->container['total_record_count'] === null) {
            $invalid_properties[] = "'total_record_count' can't be null";
        }
        if ($this->container['message_id'] === null) {
            $invalid_properties[] = "'message_id' can't be null";
        }
        if ($this->container['status_desc'] === null) {
            $invalid_properties[] = "'status_desc' can't be null";
        }
        if ($this->container['status_code'] === null) {
            $invalid_properties[] = "'status_code' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['has_more_elements'] === null) {
            return false;
        }
        if ($this->container['result_set_no'] === null) {
            return false;
        }
        if ($this->container['total_record_count'] === null) {
            return false;
        }
        if ($this->container['message_id'] === null) {
            return false;
        }
        if ($this->container['status_desc'] === null) {
            return false;
        }
        if ($this->container['status_code'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets has_more_elements
     * @return string
     */
    public function getHasMoreElements()
    {
        return $this->container['has_more_elements'];
    }

    /**
     * Sets has_more_elements
     * @param string $has_more_elements Value is \"Y\" if more records available. Value is \"N\" if there are no more records available.
     * @return $this
     */
    public function setHasMoreElements($has_more_elements)
    {
        $this->container['has_more_elements'] = $has_more_elements;

        return $this;
    }

    /**
     * Gets result_set_no
     * @return string
     */
    public function getResultSetNo()
    {
        return $this->container['result_set_no'];
    }

    /**
     * Sets result_set_no
     * @param string $result_set_no Result Set Number.
     * @return $this
     */
    public function setResultSetNo($result_set_no)
    {
        $this->container['result_set_no'] = $result_set_no;

        return $this;
    }

    /**
     * Gets total_record_count
     * @return string
     */
    public function getTotalRecordCount()
    {
        return $this->container['total_record_count'];
    }

    /**
     * Sets total_record_count
     * @param string $total_record_count Total Payment Records Count for the requested parameters.
     * @return $this
     */
    public function setTotalRecordCount($total_record_count)
    {
        $this->container['total_record_count'] = $total_record_count;

        return $this;
    }

    /**
     * Gets payments
     * @return \vpa_102\model\Payments
     */
    public function getPayments()
    {
        return $this->container['payments'];
    }

    /**
     * Sets payments
     * @param \vpa_102\model\Payments $payments
     * @return $this
     */
    public function setPayments($payments)
    {
        $this->container['payments'] = $payments;

        return $this;
    }

    /**
     * Gets message_id
     * @return string
     */
    public function getMessageId()
    {
        return $this->container['message_id'];
    }

    /**
     * Sets message_id
     * @param string $message_id Unique identifier which was sent in the request.
     * @return $this
     */
    public function setMessageId($message_id)
    {
        $this->container['message_id'] = $message_id;

        return $this;
    }

    /**
     * Gets status_desc
     * @return string
     */
    public function getStatusDesc()
    {
        return $this->container['status_desc'];
    }

    /**
     * Sets status_desc
     * @param string $status_desc Status description of the response.
     * @return $this
     */
    public function setStatusDesc($status_desc)
    {
        $this->container['status_desc'] = $status_desc;

        return $this;
    }

    /**
     * Gets status_code
     * @return string
     */
    public function getStatusCode()
    {
        return $this->container['status_code'];
    }

    /**
     * Sets status_code
     * @param string $status_code Status code of the response. It is alphanumeric. The values are specific to each method.  For the details of the various error codes returned for this method refer to the \"Error Codes\" table below.
     * @return $this
     */
    public function setStatusCode($status_code)
    {
        $this->container['status_code'] = $status_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\vpa_102\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\vpa_102\ObjectSerializer::sanitizeForSerialization($this));
    }
}

/**
* ----------------------------------------------------------------------------------------------------------------------
*
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
* ----------------------------------------------------------------------------------------------------------------------
*/