<?php
/**
 * OffersInner
 *
 * PHP version 5
 *
 * @category Class
 * @package  vmorc_100
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Offers Data API
 *
 * The Offers Data API provides developers a quick and easy way to retrieve offer information from VMORC. The API allows you to retrieve all your available offers or retrieve specific offers. In an offer-specific request, you may choose to filter your accessible offers by certain offer attributes or you may request for offers by its identifiers.
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace vmorc_100\model;

use \ArrayAccess;

/**
 * OffersInner Class Doc Comment
 *
 * @category    Class
 * @package     vmorc_100
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OffersInner implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Offers_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'is_offer_event' => 'bool',
        'merchant_terms' => '\vmorc_100\model\MerchantTerms',
        'program_name' => 'string',
        'barcode' => '\vmorc_100\model\Barcode',
        'promoting_countries' => '\vmorc_100\model\PromotingCountries',
        'offer_metadata' => '\vmorc_100\model\OfferMetadata',
        'offer_source_contact' => 'string',
        'offer_id' => 'int',
        'redemption_url' => 'string',
        'creative_guidelines' => 'string',
        'offer_type' => '\vmorc_100\model\OfferType',
        'offer_source' => 'string',
        'featured_offer_indicator' => 'bool',
        'sup_data4' => '\vmorc_100\model\SupData4',
        'redemption_countries' => '\vmorc_100\model\RedemptionCountries',
        'merchant_list' => '\vmorc_100\model\MerchantList',
        'redemption_email' => 'string',
        'sup_data2' => '\vmorc_100\model\SupData2',
        'sup_data3' => '\vmorc_100\model\SupData3',
        'offer_content_id' => 'int',
        'last_modified_date_time' => 'string',
        'promotion_restictions' => '\vmorc_100\model\PromotionRestictions',
        'language_id' => 'int',
        'redemption_format_instructions' => 'string',
        'offer_title' => 'string',
        'promotion_to_date' => 'string',
        'promotion_from_date' => 'string',
        'f_a_qs' => '\vmorc_100\model\FAQs',
        'sup_data1' => '\vmorc_100\model\SupData1',
        'current_version' => 'int',
        'qr_code' => '\vmorc_100\model\QrCode',
        'creative_approvals_email' => 'string',
        'image_list' => '\vmorc_100\model\ImageList',
        'business_segment_list' => '\vmorc_100\model\BusinessSegmentList',
        'category_subcategory_list' => '\vmorc_100\model\CategorySubcategoryList',
        'validity_to_date' => 'string',
        'offer_copy' => '\vmorc_100\model\OfferCopy',
        'visa_terms' => '\vmorc_100\model\VisaTerms',
        'offer_status' => 'string',
        'index_number' => 'int',
        'event_sub_title' => 'string',
        'offer_short_description' => '\vmorc_100\model\OfferShortDescription',
        'date_locations' => '\vmorc_100\model\DateLocations',
        'redemption_code' => 'string',
        'program_id' => 'int',
        'card_payment_type' => '\vmorc_100\model\CardPaymentType',
        'card_product_list' => '\vmorc_100\model\CardProductList',
        'accountrangestorpins' => '\vmorc_100\model\Accountrangestorpins',
        'validity_from_date' => 'string',
        'rpins' => '\vmorc_100\model\Rpins',
        'redemption_channel_list' => '\vmorc_100\model\RedemptionChannelList',
        'active_indicator' => 'bool',
        'social_media_sharing_types' => '\vmorc_100\model\SocialMediaSharingTypes',
        'promotion_channel_list' => '\vmorc_100\model\PromotionChannelList',
        'accountranges' => '\vmorc_100\model\Accountranges',
        'share_title' => 'string',
        'redemption_telephone' => '\vmorc_100\model\RedemptionTelephone',
        'language' => 'string',
        'binstorpins' => '\vmorc_100\model\Binstorpins',
        'legal_country_exclusions' => '\vmorc_100\model\LegalCountryExclusions',
        'sold_out' => 'bool',
        'bins' => '\vmorc_100\model\Bins'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'is_offer_event' => 'isOfferEvent',
        'merchant_terms' => 'merchantTerms',
        'program_name' => 'programName',
        'barcode' => 'barcode',
        'promoting_countries' => 'promotingCountries',
        'offer_metadata' => 'offerMetadata',
        'offer_source_contact' => 'offerSourceContact',
        'offer_id' => 'offerId',
        'redemption_url' => 'redemptionUrl',
        'creative_guidelines' => 'creativeGuidelines',
        'offer_type' => 'offerType',
        'offer_source' => 'offerSource',
        'featured_offer_indicator' => 'featuredOfferIndicator',
        'sup_data4' => 'supData4',
        'redemption_countries' => 'redemptionCountries',
        'merchant_list' => 'merchantList',
        'redemption_email' => 'redemptionEmail',
        'sup_data2' => 'supData2',
        'sup_data3' => 'supData3',
        'offer_content_id' => 'offerContentId',
        'last_modified_date_time' => 'lastModifiedDateTime',
        'promotion_restictions' => 'promotionRestictions',
        'language_id' => 'languageId',
        'redemption_format_instructions' => 'redemptionFormatInstructions',
        'offer_title' => 'offerTitle',
        'promotion_to_date' => 'promotionToDate',
        'promotion_from_date' => 'promotionFromDate',
        'f_a_qs' => 'fAQs',
        'sup_data1' => 'supData1',
        'current_version' => 'currentVersion',
        'qr_code' => 'qrCode',
        'creative_approvals_email' => 'creativeApprovalsEmail',
        'image_list' => 'imageList',
        'business_segment_list' => 'businessSegmentList',
        'category_subcategory_list' => 'categorySubcategoryList',
        'validity_to_date' => 'validityToDate',
        'offer_copy' => 'offerCopy',
        'visa_terms' => 'visaTerms',
        'offer_status' => 'offerStatus',
        'index_number' => 'indexNumber',
        'event_sub_title' => 'eventSubTitle',
        'offer_short_description' => 'offerShortDescription',
        'date_locations' => 'dateLocations',
        'redemption_code' => 'redemptionCode',
        'program_id' => 'programId',
        'card_payment_type' => 'cardPaymentType',
        'card_product_list' => 'cardProductList',
        'accountrangestorpins' => 'accountrangestorpins',
        'validity_from_date' => 'validityFromDate',
        'rpins' => 'rpins',
        'redemption_channel_list' => 'redemptionChannelList',
        'active_indicator' => 'activeIndicator',
        'social_media_sharing_types' => 'socialMediaSharingTypes',
        'promotion_channel_list' => 'promotionChannelList',
        'accountranges' => 'accountranges',
        'share_title' => 'shareTitle',
        'redemption_telephone' => 'redemptionTelephone',
        'language' => 'language',
        'binstorpins' => 'binstorpins',
        'legal_country_exclusions' => 'legalCountryExclusions',
        'sold_out' => 'soldOut',
        'bins' => 'bins'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'is_offer_event' => 'setIsOfferEvent',
        'merchant_terms' => 'setMerchantTerms',
        'program_name' => 'setProgramName',
        'barcode' => 'setBarcode',
        'promoting_countries' => 'setPromotingCountries',
        'offer_metadata' => 'setOfferMetadata',
        'offer_source_contact' => 'setOfferSourceContact',
        'offer_id' => 'setOfferId',
        'redemption_url' => 'setRedemptionUrl',
        'creative_guidelines' => 'setCreativeGuidelines',
        'offer_type' => 'setOfferType',
        'offer_source' => 'setOfferSource',
        'featured_offer_indicator' => 'setFeaturedOfferIndicator',
        'sup_data4' => 'setSupData4',
        'redemption_countries' => 'setRedemptionCountries',
        'merchant_list' => 'setMerchantList',
        'redemption_email' => 'setRedemptionEmail',
        'sup_data2' => 'setSupData2',
        'sup_data3' => 'setSupData3',
        'offer_content_id' => 'setOfferContentId',
        'last_modified_date_time' => 'setLastModifiedDateTime',
        'promotion_restictions' => 'setPromotionRestictions',
        'language_id' => 'setLanguageId',
        'redemption_format_instructions' => 'setRedemptionFormatInstructions',
        'offer_title' => 'setOfferTitle',
        'promotion_to_date' => 'setPromotionToDate',
        'promotion_from_date' => 'setPromotionFromDate',
        'f_a_qs' => 'setFAQs',
        'sup_data1' => 'setSupData1',
        'current_version' => 'setCurrentVersion',
        'qr_code' => 'setQrCode',
        'creative_approvals_email' => 'setCreativeApprovalsEmail',
        'image_list' => 'setImageList',
        'business_segment_list' => 'setBusinessSegmentList',
        'category_subcategory_list' => 'setCategorySubcategoryList',
        'validity_to_date' => 'setValidityToDate',
        'offer_copy' => 'setOfferCopy',
        'visa_terms' => 'setVisaTerms',
        'offer_status' => 'setOfferStatus',
        'index_number' => 'setIndexNumber',
        'event_sub_title' => 'setEventSubTitle',
        'offer_short_description' => 'setOfferShortDescription',
        'date_locations' => 'setDateLocations',
        'redemption_code' => 'setRedemptionCode',
        'program_id' => 'setProgramId',
        'card_payment_type' => 'setCardPaymentType',
        'card_product_list' => 'setCardProductList',
        'accountrangestorpins' => 'setAccountrangestorpins',
        'validity_from_date' => 'setValidityFromDate',
        'rpins' => 'setRpins',
        'redemption_channel_list' => 'setRedemptionChannelList',
        'active_indicator' => 'setActiveIndicator',
        'social_media_sharing_types' => 'setSocialMediaSharingTypes',
        'promotion_channel_list' => 'setPromotionChannelList',
        'accountranges' => 'setAccountranges',
        'share_title' => 'setShareTitle',
        'redemption_telephone' => 'setRedemptionTelephone',
        'language' => 'setLanguage',
        'binstorpins' => 'setBinstorpins',
        'legal_country_exclusions' => 'setLegalCountryExclusions',
        'sold_out' => 'setSoldOut',
        'bins' => 'setBins'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'is_offer_event' => 'getIsOfferEvent',
        'merchant_terms' => 'getMerchantTerms',
        'program_name' => 'getProgramName',
        'barcode' => 'getBarcode',
        'promoting_countries' => 'getPromotingCountries',
        'offer_metadata' => 'getOfferMetadata',
        'offer_source_contact' => 'getOfferSourceContact',
        'offer_id' => 'getOfferId',
        'redemption_url' => 'getRedemptionUrl',
        'creative_guidelines' => 'getCreativeGuidelines',
        'offer_type' => 'getOfferType',
        'offer_source' => 'getOfferSource',
        'featured_offer_indicator' => 'getFeaturedOfferIndicator',
        'sup_data4' => 'getSupData4',
        'redemption_countries' => 'getRedemptionCountries',
        'merchant_list' => 'getMerchantList',
        'redemption_email' => 'getRedemptionEmail',
        'sup_data2' => 'getSupData2',
        'sup_data3' => 'getSupData3',
        'offer_content_id' => 'getOfferContentId',
        'last_modified_date_time' => 'getLastModifiedDateTime',
        'promotion_restictions' => 'getPromotionRestictions',
        'language_id' => 'getLanguageId',
        'redemption_format_instructions' => 'getRedemptionFormatInstructions',
        'offer_title' => 'getOfferTitle',
        'promotion_to_date' => 'getPromotionToDate',
        'promotion_from_date' => 'getPromotionFromDate',
        'f_a_qs' => 'getFAQs',
        'sup_data1' => 'getSupData1',
        'current_version' => 'getCurrentVersion',
        'qr_code' => 'getQrCode',
        'creative_approvals_email' => 'getCreativeApprovalsEmail',
        'image_list' => 'getImageList',
        'business_segment_list' => 'getBusinessSegmentList',
        'category_subcategory_list' => 'getCategorySubcategoryList',
        'validity_to_date' => 'getValidityToDate',
        'offer_copy' => 'getOfferCopy',
        'visa_terms' => 'getVisaTerms',
        'offer_status' => 'getOfferStatus',
        'index_number' => 'getIndexNumber',
        'event_sub_title' => 'getEventSubTitle',
        'offer_short_description' => 'getOfferShortDescription',
        'date_locations' => 'getDateLocations',
        'redemption_code' => 'getRedemptionCode',
        'program_id' => 'getProgramId',
        'card_payment_type' => 'getCardPaymentType',
        'card_product_list' => 'getCardProductList',
        'accountrangestorpins' => 'getAccountrangestorpins',
        'validity_from_date' => 'getValidityFromDate',
        'rpins' => 'getRpins',
        'redemption_channel_list' => 'getRedemptionChannelList',
        'active_indicator' => 'getActiveIndicator',
        'social_media_sharing_types' => 'getSocialMediaSharingTypes',
        'promotion_channel_list' => 'getPromotionChannelList',
        'accountranges' => 'getAccountranges',
        'share_title' => 'getShareTitle',
        'redemption_telephone' => 'getRedemptionTelephone',
        'language' => 'getLanguage',
        'binstorpins' => 'getBinstorpins',
        'legal_country_exclusions' => 'getLegalCountryExclusions',
        'sold_out' => 'getSoldOut',
        'bins' => 'getBins'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['is_offer_event'] = isset($data['is_offer_event']) ? $data['is_offer_event'] : null;
        $this->container['merchant_terms'] = isset($data['merchant_terms']) ? $data['merchant_terms'] : null;
        $this->container['program_name'] = isset($data['program_name']) ? $data['program_name'] : null;
        $this->container['barcode'] = isset($data['barcode']) ? $data['barcode'] : null;
        $this->container['promoting_countries'] = isset($data['promoting_countries']) ? $data['promoting_countries'] : null;
        $this->container['offer_metadata'] = isset($data['offer_metadata']) ? $data['offer_metadata'] : null;
        $this->container['offer_source_contact'] = isset($data['offer_source_contact']) ? $data['offer_source_contact'] : null;
        $this->container['offer_id'] = isset($data['offer_id']) ? $data['offer_id'] : null;
        $this->container['redemption_url'] = isset($data['redemption_url']) ? $data['redemption_url'] : null;
        $this->container['creative_guidelines'] = isset($data['creative_guidelines']) ? $data['creative_guidelines'] : null;
        $this->container['offer_type'] = isset($data['offer_type']) ? $data['offer_type'] : null;
        $this->container['offer_source'] = isset($data['offer_source']) ? $data['offer_source'] : null;
        $this->container['featured_offer_indicator'] = isset($data['featured_offer_indicator']) ? $data['featured_offer_indicator'] : null;
        $this->container['sup_data4'] = isset($data['sup_data4']) ? $data['sup_data4'] : null;
        $this->container['redemption_countries'] = isset($data['redemption_countries']) ? $data['redemption_countries'] : null;
        $this->container['merchant_list'] = isset($data['merchant_list']) ? $data['merchant_list'] : null;
        $this->container['redemption_email'] = isset($data['redemption_email']) ? $data['redemption_email'] : null;
        $this->container['sup_data2'] = isset($data['sup_data2']) ? $data['sup_data2'] : null;
        $this->container['sup_data3'] = isset($data['sup_data3']) ? $data['sup_data3'] : null;
        $this->container['offer_content_id'] = isset($data['offer_content_id']) ? $data['offer_content_id'] : null;
        $this->container['last_modified_date_time'] = isset($data['last_modified_date_time']) ? $data['last_modified_date_time'] : null;
        $this->container['promotion_restictions'] = isset($data['promotion_restictions']) ? $data['promotion_restictions'] : null;
        $this->container['language_id'] = isset($data['language_id']) ? $data['language_id'] : null;
        $this->container['redemption_format_instructions'] = isset($data['redemption_format_instructions']) ? $data['redemption_format_instructions'] : null;
        $this->container['offer_title'] = isset($data['offer_title']) ? $data['offer_title'] : null;
        $this->container['promotion_to_date'] = isset($data['promotion_to_date']) ? $data['promotion_to_date'] : null;
        $this->container['promotion_from_date'] = isset($data['promotion_from_date']) ? $data['promotion_from_date'] : null;
        $this->container['f_a_qs'] = isset($data['f_a_qs']) ? $data['f_a_qs'] : null;
        $this->container['sup_data1'] = isset($data['sup_data1']) ? $data['sup_data1'] : null;
        $this->container['current_version'] = isset($data['current_version']) ? $data['current_version'] : null;
        $this->container['qr_code'] = isset($data['qr_code']) ? $data['qr_code'] : null;
        $this->container['creative_approvals_email'] = isset($data['creative_approvals_email']) ? $data['creative_approvals_email'] : null;
        $this->container['image_list'] = isset($data['image_list']) ? $data['image_list'] : null;
        $this->container['business_segment_list'] = isset($data['business_segment_list']) ? $data['business_segment_list'] : null;
        $this->container['category_subcategory_list'] = isset($data['category_subcategory_list']) ? $data['category_subcategory_list'] : null;
        $this->container['validity_to_date'] = isset($data['validity_to_date']) ? $data['validity_to_date'] : null;
        $this->container['offer_copy'] = isset($data['offer_copy']) ? $data['offer_copy'] : null;
        $this->container['visa_terms'] = isset($data['visa_terms']) ? $data['visa_terms'] : null;
        $this->container['offer_status'] = isset($data['offer_status']) ? $data['offer_status'] : null;
        $this->container['index_number'] = isset($data['index_number']) ? $data['index_number'] : null;
        $this->container['event_sub_title'] = isset($data['event_sub_title']) ? $data['event_sub_title'] : null;
        $this->container['offer_short_description'] = isset($data['offer_short_description']) ? $data['offer_short_description'] : null;
        $this->container['date_locations'] = isset($data['date_locations']) ? $data['date_locations'] : null;
        $this->container['redemption_code'] = isset($data['redemption_code']) ? $data['redemption_code'] : null;
        $this->container['program_id'] = isset($data['program_id']) ? $data['program_id'] : null;
        $this->container['card_payment_type'] = isset($data['card_payment_type']) ? $data['card_payment_type'] : null;
        $this->container['card_product_list'] = isset($data['card_product_list']) ? $data['card_product_list'] : null;
        $this->container['accountrangestorpins'] = isset($data['accountrangestorpins']) ? $data['accountrangestorpins'] : null;
        $this->container['validity_from_date'] = isset($data['validity_from_date']) ? $data['validity_from_date'] : null;
        $this->container['rpins'] = isset($data['rpins']) ? $data['rpins'] : null;
        $this->container['redemption_channel_list'] = isset($data['redemption_channel_list']) ? $data['redemption_channel_list'] : null;
        $this->container['active_indicator'] = isset($data['active_indicator']) ? $data['active_indicator'] : null;
        $this->container['social_media_sharing_types'] = isset($data['social_media_sharing_types']) ? $data['social_media_sharing_types'] : null;
        $this->container['promotion_channel_list'] = isset($data['promotion_channel_list']) ? $data['promotion_channel_list'] : null;
        $this->container['accountranges'] = isset($data['accountranges']) ? $data['accountranges'] : null;
        $this->container['share_title'] = isset($data['share_title']) ? $data['share_title'] : null;
        $this->container['redemption_telephone'] = isset($data['redemption_telephone']) ? $data['redemption_telephone'] : null;
        $this->container['language'] = isset($data['language']) ? $data['language'] : null;
        $this->container['binstorpins'] = isset($data['binstorpins']) ? $data['binstorpins'] : null;
        $this->container['legal_country_exclusions'] = isset($data['legal_country_exclusions']) ? $data['legal_country_exclusions'] : null;
        $this->container['sold_out'] = isset($data['sold_out']) ? $data['sold_out'] : null;
        $this->container['bins'] = isset($data['bins']) ? $data['bins'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets is_offer_event
     * @return bool
     */
    public function getIsOfferEvent()
    {
        return $this->container['is_offer_event'];
    }

    /**
     * Sets is_offer_event
     * @param bool $is_offer_event the indicator to specify that the offer is an event
     * @return $this
     */
    public function setIsOfferEvent($is_offer_event)
    {
        $this->container['is_offer_event'] = $is_offer_event;

        return $this;
    }

    /**
     * Gets merchant_terms
     * @return \vmorc_100\model\MerchantTerms
     */
    public function getMerchantTerms()
    {
        return $this->container['merchant_terms'];
    }

    /**
     * Sets merchant_terms
     * @param \vmorc_100\model\MerchantTerms $merchant_terms
     * @return $this
     */
    public function setMerchantTerms($merchant_terms)
    {
        $this->container['merchant_terms'] = $merchant_terms;

        return $this;
    }

    /**
     * Gets program_name
     * @return string
     */
    public function getProgramName()
    {
        return $this->container['program_name'];
    }

    /**
     * Sets program_name
     * @param string $program_name the name of the program. Max length: 500 characters.
     * @return $this
     */
    public function setProgramName($program_name)
    {
        $this->container['program_name'] = $program_name;

        return $this;
    }

    /**
     * Gets barcode
     * @return \vmorc_100\model\Barcode
     */
    public function getBarcode()
    {
        return $this->container['barcode'];
    }

    /**
     * Sets barcode
     * @param \vmorc_100\model\Barcode $barcode
     * @return $this
     */
    public function setBarcode($barcode)
    {
        $this->container['barcode'] = $barcode;

        return $this;
    }

    /**
     * Gets promoting_countries
     * @return \vmorc_100\model\PromotingCountries
     */
    public function getPromotingCountries()
    {
        return $this->container['promoting_countries'];
    }

    /**
     * Sets promoting_countries
     * @param \vmorc_100\model\PromotingCountries $promoting_countries
     * @return $this
     */
    public function setPromotingCountries($promoting_countries)
    {
        $this->container['promoting_countries'] = $promoting_countries;

        return $this;
    }

    /**
     * Gets offer_metadata
     * @return \vmorc_100\model\OfferMetadata
     */
    public function getOfferMetadata()
    {
        return $this->container['offer_metadata'];
    }

    /**
     * Sets offer_metadata
     * @param \vmorc_100\model\OfferMetadata $offer_metadata
     * @return $this
     */
    public function setOfferMetadata($offer_metadata)
    {
        $this->container['offer_metadata'] = $offer_metadata;

        return $this;
    }

    /**
     * Gets offer_source_contact
     * @return string
     */
    public function getOfferSourceContact()
    {
        return $this->container['offer_source_contact'];
    }

    /**
     * Sets offer_source_contact
     * @param string $offer_source_contact the source agency contact asssociated with the offer. Max length: 100 characters
     * @return $this
     */
    public function setOfferSourceContact($offer_source_contact)
    {
        $this->container['offer_source_contact'] = $offer_source_contact;

        return $this;
    }

    /**
     * Gets offer_id
     * @return int
     */
    public function getOfferId()
    {
        return $this->container['offer_id'];
    }

    /**
     * Sets offer_id
     * @param int $offer_id an identifier for the offer and any translations it may have
     * @return $this
     */
    public function setOfferId($offer_id)
    {
        $this->container['offer_id'] = $offer_id;

        return $this;
    }

    /**
     * Gets redemption_url
     * @return string
     */
    public function getRedemptionUrl()
    {
        return $this->container['redemption_url'];
    }

    /**
     * Sets redemption_url
     * @param string $redemption_url the redemption URL of the offer. May return an empty String. Max length: 2048 characters
     * @return $this
     */
    public function setRedemptionUrl($redemption_url)
    {
        $this->container['redemption_url'] = $redemption_url;

        return $this;
    }

    /**
     * Gets creative_guidelines
     * @return string
     */
    public function getCreativeGuidelines()
    {
        return $this->container['creative_guidelines'];
    }

    /**
     * Sets creative_guidelines
     * @param string $creative_guidelines the creative guidelines of the offer. May return an empty String. Max length: 2GB
     * @return $this
     */
    public function setCreativeGuidelines($creative_guidelines)
    {
        $this->container['creative_guidelines'] = $creative_guidelines;

        return $this;
    }

    /**
     * Gets offer_type
     * @return \vmorc_100\model\OfferType
     */
    public function getOfferType()
    {
        return $this->container['offer_type'];
    }

    /**
     * Sets offer_type
     * @param \vmorc_100\model\OfferType $offer_type
     * @return $this
     */
    public function setOfferType($offer_type)
    {
        $this->container['offer_type'] = $offer_type;

        return $this;
    }

    /**
     * Gets offer_source
     * @return string
     */
    public function getOfferSource()
    {
        return $this->container['offer_source'];
    }

    /**
     * Sets offer_source
     * @param string $offer_source the source agency asssociated with the offer. Max length: 200 characters
     * @return $this
     */
    public function setOfferSource($offer_source)
    {
        $this->container['offer_source'] = $offer_source;

        return $this;
    }

    /**
     * Gets featured_offer_indicator
     * @return bool
     */
    public function getFeaturedOfferIndicator()
    {
        return $this->container['featured_offer_indicator'];
    }

    /**
     * Sets featured_offer_indicator
     * @param bool $featured_offer_indicator indicator whether the offer is featured
     * @return $this
     */
    public function setFeaturedOfferIndicator($featured_offer_indicator)
    {
        $this->container['featured_offer_indicator'] = $featured_offer_indicator;

        return $this;
    }

    /**
     * Gets sup_data4
     * @return \vmorc_100\model\SupData4
     */
    public function getSupData4()
    {
        return $this->container['sup_data4'];
    }

    /**
     * Sets sup_data4
     * @param \vmorc_100\model\SupData4 $sup_data4
     * @return $this
     */
    public function setSupData4($sup_data4)
    {
        $this->container['sup_data4'] = $sup_data4;

        return $this;
    }

    /**
     * Gets redemption_countries
     * @return \vmorc_100\model\RedemptionCountries
     */
    public function getRedemptionCountries()
    {
        return $this->container['redemption_countries'];
    }

    /**
     * Sets redemption_countries
     * @param \vmorc_100\model\RedemptionCountries $redemption_countries
     * @return $this
     */
    public function setRedemptionCountries($redemption_countries)
    {
        $this->container['redemption_countries'] = $redemption_countries;

        return $this;
    }

    /**
     * Gets merchant_list
     * @return \vmorc_100\model\MerchantList
     */
    public function getMerchantList()
    {
        return $this->container['merchant_list'];
    }

    /**
     * Sets merchant_list
     * @param \vmorc_100\model\MerchantList $merchant_list
     * @return $this
     */
    public function setMerchantList($merchant_list)
    {
        $this->container['merchant_list'] = $merchant_list;

        return $this;
    }

    /**
     * Gets redemption_email
     * @return string
     */
    public function getRedemptionEmail()
    {
        return $this->container['redemption_email'];
    }

    /**
     * Sets redemption_email
     * @param string $redemption_email the redemption Email of the offer. May return an empty String. Max length: 2048 characters
     * @return $this
     */
    public function setRedemptionEmail($redemption_email)
    {
        $this->container['redemption_email'] = $redemption_email;

        return $this;
    }

    /**
     * Gets sup_data2
     * @return \vmorc_100\model\SupData2
     */
    public function getSupData2()
    {
        return $this->container['sup_data2'];
    }

    /**
     * Sets sup_data2
     * @param \vmorc_100\model\SupData2 $sup_data2
     * @return $this
     */
    public function setSupData2($sup_data2)
    {
        $this->container['sup_data2'] = $sup_data2;

        return $this;
    }

    /**
     * Gets sup_data3
     * @return \vmorc_100\model\SupData3
     */
    public function getSupData3()
    {
        return $this->container['sup_data3'];
    }

    /**
     * Sets sup_data3
     * @param \vmorc_100\model\SupData3 $sup_data3
     * @return $this
     */
    public function setSupData3($sup_data3)
    {
        $this->container['sup_data3'] = $sup_data3;

        return $this;
    }

    /**
     * Gets offer_content_id
     * @return int
     */
    public function getOfferContentId()
    {
        return $this->container['offer_content_id'];
    }

    /**
     * Sets offer_content_id
     * @param int $offer_content_id a unique identifier for the offer for the specific version and specified language
     * @return $this
     */
    public function setOfferContentId($offer_content_id)
    {
        $this->container['offer_content_id'] = $offer_content_id;

        return $this;
    }

    /**
     * Gets last_modified_date_time
     * @return string
     */
    public function getLastModifiedDateTime()
    {
        return $this->container['last_modified_date_time'];
    }

    /**
     * Sets last_modified_date_time
     * @param string $last_modified_date_time the date and time the offer was last updated. Formatted as : DayOfWeek, DD Mon YYYY HH:MM:SS GMT
     * @return $this
     */
    public function setLastModifiedDateTime($last_modified_date_time)
    {
        $this->container['last_modified_date_time'] = $last_modified_date_time;

        return $this;
    }

    /**
     * Gets promotion_restictions
     * @return \vmorc_100\model\PromotionRestictions
     */
    public function getPromotionRestictions()
    {
        return $this->container['promotion_restictions'];
    }

    /**
     * Sets promotion_restictions
     * @param \vmorc_100\model\PromotionRestictions $promotion_restictions
     * @return $this
     */
    public function setPromotionRestictions($promotion_restictions)
    {
        $this->container['promotion_restictions'] = $promotion_restictions;

        return $this;
    }

    /**
     * Gets language_id
     * @return int
     */
    public function getLanguageId()
    {
        return $this->container['language_id'];
    }

    /**
     * Sets language_id
     * @param int $language_id the identifier for the language of the offer
     * @return $this
     */
    public function setLanguageId($language_id)
    {
        $this->container['language_id'] = $language_id;

        return $this;
    }

    /**
     * Gets redemption_format_instructions
     * @return string
     */
    public function getRedemptionFormatInstructions()
    {
        return $this->container['redemption_format_instructions'];
    }

    /**
     * Sets redemption_format_instructions
     * @param string $redemption_format_instructions the format instructions for redemption of offer. May return an empty String. Max length: 2048 characters
     * @return $this
     */
    public function setRedemptionFormatInstructions($redemption_format_instructions)
    {
        $this->container['redemption_format_instructions'] = $redemption_format_instructions;

        return $this;
    }

    /**
     * Gets offer_title
     * @return string
     */
    public function getOfferTitle()
    {
        return $this->container['offer_title'];
    }

    /**
     * Sets offer_title
     * @param string $offer_title the title of the offer. Max length: 1000 characters
     * @return $this
     */
    public function setOfferTitle($offer_title)
    {
        $this->container['offer_title'] = $offer_title;

        return $this;
    }

    /**
     * Gets promotion_to_date
     * @return string
     */
    public function getPromotionToDate()
    {
        return $this->container['promotion_to_date'];
    }

    /**
     * Sets promotion_to_date
     * @param string $promotion_to_date the end of the promotion date range (in GMT). Formatted as: Mon DD, YYYY
     * @return $this
     */
    public function setPromotionToDate($promotion_to_date)
    {
        $this->container['promotion_to_date'] = $promotion_to_date;

        return $this;
    }

    /**
     * Gets promotion_from_date
     * @return string
     */
    public function getPromotionFromDate()
    {
        return $this->container['promotion_from_date'];
    }

    /**
     * Sets promotion_from_date
     * @param string $promotion_from_date the start of the promotion date range (in GMT). Formatted as: Mon DD, YYYY
     * @return $this
     */
    public function setPromotionFromDate($promotion_from_date)
    {
        $this->container['promotion_from_date'] = $promotion_from_date;

        return $this;
    }

    /**
     * Gets f_a_qs
     * @return \vmorc_100\model\FAQs
     */
    public function getFAQs()
    {
        return $this->container['f_a_qs'];
    }

    /**
     * Sets f_a_qs
     * @param \vmorc_100\model\FAQs $f_a_qs
     * @return $this
     */
    public function setFAQs($f_a_qs)
    {
        $this->container['f_a_qs'] = $f_a_qs;

        return $this;
    }

    /**
     * Gets sup_data1
     * @return \vmorc_100\model\SupData1
     */
    public function getSupData1()
    {
        return $this->container['sup_data1'];
    }

    /**
     * Sets sup_data1
     * @param \vmorc_100\model\SupData1 $sup_data1
     * @return $this
     */
    public function setSupData1($sup_data1)
    {
        $this->container['sup_data1'] = $sup_data1;

        return $this;
    }

    /**
     * Gets current_version
     * @return int
     */
    public function getCurrentVersion()
    {
        return $this->container['current_version'];
    }

    /**
     * Sets current_version
     * @param int $current_version the version of the offer
     * @return $this
     */
    public function setCurrentVersion($current_version)
    {
        $this->container['current_version'] = $current_version;

        return $this;
    }

    /**
     * Gets qr_code
     * @return \vmorc_100\model\QrCode
     */
    public function getQrCode()
    {
        return $this->container['qr_code'];
    }

    /**
     * Sets qr_code
     * @param \vmorc_100\model\QrCode $qr_code
     * @return $this
     */
    public function setQrCode($qr_code)
    {
        $this->container['qr_code'] = $qr_code;

        return $this;
    }

    /**
     * Gets creative_approvals_email
     * @return string
     */
    public function getCreativeApprovalsEmail()
    {
        return $this->container['creative_approvals_email'];
    }

    /**
     * Sets creative_approvals_email
     * @param string $creative_approvals_email the email of the creative approval of the offer. May return an empty String. Max length: 200 characters
     * @return $this
     */
    public function setCreativeApprovalsEmail($creative_approvals_email)
    {
        $this->container['creative_approvals_email'] = $creative_approvals_email;

        return $this;
    }

    /**
     * Gets image_list
     * @return \vmorc_100\model\ImageList
     */
    public function getImageList()
    {
        return $this->container['image_list'];
    }

    /**
     * Sets image_list
     * @param \vmorc_100\model\ImageList $image_list
     * @return $this
     */
    public function setImageList($image_list)
    {
        $this->container['image_list'] = $image_list;

        return $this;
    }

    /**
     * Gets business_segment_list
     * @return \vmorc_100\model\BusinessSegmentList
     */
    public function getBusinessSegmentList()
    {
        return $this->container['business_segment_list'];
    }

    /**
     * Sets business_segment_list
     * @param \vmorc_100\model\BusinessSegmentList $business_segment_list
     * @return $this
     */
    public function setBusinessSegmentList($business_segment_list)
    {
        $this->container['business_segment_list'] = $business_segment_list;

        return $this;
    }

    /**
     * Gets category_subcategory_list
     * @return \vmorc_100\model\CategorySubcategoryList
     */
    public function getCategorySubcategoryList()
    {
        return $this->container['category_subcategory_list'];
    }

    /**
     * Sets category_subcategory_list
     * @param \vmorc_100\model\CategorySubcategoryList $category_subcategory_list
     * @return $this
     */
    public function setCategorySubcategoryList($category_subcategory_list)
    {
        $this->container['category_subcategory_list'] = $category_subcategory_list;

        return $this;
    }

    /**
     * Gets validity_to_date
     * @return string
     */
    public function getValidityToDate()
    {
        return $this->container['validity_to_date'];
    }

    /**
     * Sets validity_to_date
     * @param string $validity_to_date the end of the validity date range (in GMT). Formatted as: Mon DD, YYYY
     * @return $this
     */
    public function setValidityToDate($validity_to_date)
    {
        $this->container['validity_to_date'] = $validity_to_date;

        return $this;
    }

    /**
     * Gets offer_copy
     * @return \vmorc_100\model\OfferCopy
     */
    public function getOfferCopy()
    {
        return $this->container['offer_copy'];
    }

    /**
     * Sets offer_copy
     * @param \vmorc_100\model\OfferCopy $offer_copy
     * @return $this
     */
    public function setOfferCopy($offer_copy)
    {
        $this->container['offer_copy'] = $offer_copy;

        return $this;
    }

    /**
     * Gets visa_terms
     * @return \vmorc_100\model\VisaTerms
     */
    public function getVisaTerms()
    {
        return $this->container['visa_terms'];
    }

    /**
     * Sets visa_terms
     * @param \vmorc_100\model\VisaTerms $visa_terms
     * @return $this
     */
    public function setVisaTerms($visa_terms)
    {
        $this->container['visa_terms'] = $visa_terms;

        return $this;
    }

    /**
     * Gets offer_status
     * @return string
     */
    public function getOfferStatus()
    {
        return $this->container['offer_status'];
    }

    /**
     * Sets offer_status
     * @param string $offer_status the status of the offer
     * @return $this
     */
    public function setOfferStatus($offer_status)
    {
        $this->container['offer_status'] = $offer_status;

        return $this;
    }

    /**
     * Gets index_number
     * @return int
     */
    public function getIndexNumber()
    {
        return $this->container['index_number'];
    }

    /**
     * Sets index_number
     * @param int $index_number an integer identifier to signify the result index for the offer (specific to the request)
     * @return $this
     */
    public function setIndexNumber($index_number)
    {
        $this->container['index_number'] = $index_number;

        return $this;
    }

    /**
     * Gets event_sub_title
     * @return string
     */
    public function getEventSubTitle()
    {
        return $this->container['event_sub_title'];
    }

    /**
     * Sets event_sub_title
     * @param string $event_sub_title the event sub title. Returns an empty String if the offer is not an event. Field is optional for events
     * @return $this
     */
    public function setEventSubTitle($event_sub_title)
    {
        $this->container['event_sub_title'] = $event_sub_title;

        return $this;
    }

    /**
     * Gets offer_short_description
     * @return \vmorc_100\model\OfferShortDescription
     */
    public function getOfferShortDescription()
    {
        return $this->container['offer_short_description'];
    }

    /**
     * Sets offer_short_description
     * @param \vmorc_100\model\OfferShortDescription $offer_short_description
     * @return $this
     */
    public function setOfferShortDescription($offer_short_description)
    {
        $this->container['offer_short_description'] = $offer_short_description;

        return $this;
    }

    /**
     * Gets date_locations
     * @return \vmorc_100\model\DateLocations
     */
    public function getDateLocations()
    {
        return $this->container['date_locations'];
    }

    /**
     * Sets date_locations
     * @param \vmorc_100\model\DateLocations $date_locations
     * @return $this
     */
    public function setDateLocations($date_locations)
    {
        $this->container['date_locations'] = $date_locations;

        return $this;
    }

    /**
     * Gets redemption_code
     * @return string
     */
    public function getRedemptionCode()
    {
        return $this->container['redemption_code'];
    }

    /**
     * Sets redemption_code
     * @param string $redemption_code the redemption code of the offer. May return an empty String. Max length: 1024 characters
     * @return $this
     */
    public function setRedemptionCode($redemption_code)
    {
        $this->container['redemption_code'] = $redemption_code;

        return $this;
    }

    /**
     * Gets program_id
     * @return int
     */
    public function getProgramId()
    {
        return $this->container['program_id'];
    }

    /**
     * Sets program_id
     * @param int $program_id the identifier for the program
     * @return $this
     */
    public function setProgramId($program_id)
    {
        $this->container['program_id'] = $program_id;

        return $this;
    }

    /**
     * Gets card_payment_type
     * @return \vmorc_100\model\CardPaymentType
     */
    public function getCardPaymentType()
    {
        return $this->container['card_payment_type'];
    }

    /**
     * Sets card_payment_type
     * @param \vmorc_100\model\CardPaymentType $card_payment_type
     * @return $this
     */
    public function setCardPaymentType($card_payment_type)
    {
        $this->container['card_payment_type'] = $card_payment_type;

        return $this;
    }

    /**
     * Gets card_product_list
     * @return \vmorc_100\model\CardProductList
     */
    public function getCardProductList()
    {
        return $this->container['card_product_list'];
    }

    /**
     * Sets card_product_list
     * @param \vmorc_100\model\CardProductList $card_product_list
     * @return $this
     */
    public function setCardProductList($card_product_list)
    {
        $this->container['card_product_list'] = $card_product_list;

        return $this;
    }

    /**
     * Gets accountrangestorpins
     * @return \vmorc_100\model\Accountrangestorpins
     */
    public function getAccountrangestorpins()
    {
        return $this->container['accountrangestorpins'];
    }

    /**
     * Sets accountrangestorpins
     * @param \vmorc_100\model\Accountrangestorpins $accountrangestorpins
     * @return $this
     */
    public function setAccountrangestorpins($accountrangestorpins)
    {
        $this->container['accountrangestorpins'] = $accountrangestorpins;

        return $this;
    }

    /**
     * Gets validity_from_date
     * @return string
     */
    public function getValidityFromDate()
    {
        return $this->container['validity_from_date'];
    }

    /**
     * Sets validity_from_date
     * @param string $validity_from_date the start of the validity date range (in GMT). Formatted as: Mon DD, YYYY
     * @return $this
     */
    public function setValidityFromDate($validity_from_date)
    {
        $this->container['validity_from_date'] = $validity_from_date;

        return $this;
    }

    /**
     * Gets rpins
     * @return \vmorc_100\model\Rpins
     */
    public function getRpins()
    {
        return $this->container['rpins'];
    }

    /**
     * Sets rpins
     * @param \vmorc_100\model\Rpins $rpins
     * @return $this
     */
    public function setRpins($rpins)
    {
        $this->container['rpins'] = $rpins;

        return $this;
    }

    /**
     * Gets redemption_channel_list
     * @return \vmorc_100\model\RedemptionChannelList
     */
    public function getRedemptionChannelList()
    {
        return $this->container['redemption_channel_list'];
    }

    /**
     * Sets redemption_channel_list
     * @param \vmorc_100\model\RedemptionChannelList $redemption_channel_list
     * @return $this
     */
    public function setRedemptionChannelList($redemption_channel_list)
    {
        $this->container['redemption_channel_list'] = $redemption_channel_list;

        return $this;
    }

    /**
     * Gets active_indicator
     * @return bool
     */
    public function getActiveIndicator()
    {
        return $this->container['active_indicator'];
    }

    /**
     * Sets active_indicator
     * @param bool $active_indicator indicator whether offer is active
     * @return $this
     */
    public function setActiveIndicator($active_indicator)
    {
        $this->container['active_indicator'] = $active_indicator;

        return $this;
    }

    /**
     * Gets social_media_sharing_types
     * @return \vmorc_100\model\SocialMediaSharingTypes
     */
    public function getSocialMediaSharingTypes()
    {
        return $this->container['social_media_sharing_types'];
    }

    /**
     * Sets social_media_sharing_types
     * @param \vmorc_100\model\SocialMediaSharingTypes $social_media_sharing_types
     * @return $this
     */
    public function setSocialMediaSharingTypes($social_media_sharing_types)
    {
        $this->container['social_media_sharing_types'] = $social_media_sharing_types;

        return $this;
    }

    /**
     * Gets promotion_channel_list
     * @return \vmorc_100\model\PromotionChannelList
     */
    public function getPromotionChannelList()
    {
        return $this->container['promotion_channel_list'];
    }

    /**
     * Sets promotion_channel_list
     * @param \vmorc_100\model\PromotionChannelList $promotion_channel_list
     * @return $this
     */
    public function setPromotionChannelList($promotion_channel_list)
    {
        $this->container['promotion_channel_list'] = $promotion_channel_list;

        return $this;
    }

    /**
     * Gets accountranges
     * @return \vmorc_100\model\Accountranges
     */
    public function getAccountranges()
    {
        return $this->container['accountranges'];
    }

    /**
     * Sets accountranges
     * @param \vmorc_100\model\Accountranges $accountranges
     * @return $this
     */
    public function setAccountranges($accountranges)
    {
        $this->container['accountranges'] = $accountranges;

        return $this;
    }

    /**
     * Gets share_title
     * @return string
     */
    public function getShareTitle()
    {
        return $this->container['share_title'];
    }

    /**
     * Sets share_title
     * @param string $share_title the social media sharing title. Returns an empty String if the offer does not have social media sharing types.
     * @return $this
     */
    public function setShareTitle($share_title)
    {
        $this->container['share_title'] = $share_title;

        return $this;
    }

    /**
     * Gets redemption_telephone
     * @return \vmorc_100\model\RedemptionTelephone
     */
    public function getRedemptionTelephone()
    {
        return $this->container['redemption_telephone'];
    }

    /**
     * Sets redemption_telephone
     * @param \vmorc_100\model\RedemptionTelephone $redemption_telephone
     * @return $this
     */
    public function setRedemptionTelephone($redemption_telephone)
    {
        $this->container['redemption_telephone'] = $redemption_telephone;

        return $this;
    }

    /**
     * Gets language
     * @return string
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     * @param string $language the name of the language. Max length: 100 characters
     * @return $this
     */
    public function setLanguage($language)
    {
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets binstorpins
     * @return \vmorc_100\model\Binstorpins
     */
    public function getBinstorpins()
    {
        return $this->container['binstorpins'];
    }

    /**
     * Sets binstorpins
     * @param \vmorc_100\model\Binstorpins $binstorpins
     * @return $this
     */
    public function setBinstorpins($binstorpins)
    {
        $this->container['binstorpins'] = $binstorpins;

        return $this;
    }

    /**
     * Gets legal_country_exclusions
     * @return \vmorc_100\model\LegalCountryExclusions
     */
    public function getLegalCountryExclusions()
    {
        return $this->container['legal_country_exclusions'];
    }

    /**
     * Sets legal_country_exclusions
     * @param \vmorc_100\model\LegalCountryExclusions $legal_country_exclusions
     * @return $this
     */
    public function setLegalCountryExclusions($legal_country_exclusions)
    {
        $this->container['legal_country_exclusions'] = $legal_country_exclusions;

        return $this;
    }

    /**
     * Gets sold_out
     * @return bool
     */
    public function getSoldOut()
    {
        return $this->container['sold_out'];
    }

    /**
     * Sets sold_out
     * @param bool $sold_out indicator whether offer is sold out
     * @return $this
     */
    public function setSoldOut($sold_out)
    {
        $this->container['sold_out'] = $sold_out;

        return $this;
    }

    /**
     * Gets bins
     * @return \vmorc_100\model\Bins
     */
    public function getBins()
    {
        return $this->container['bins'];
    }

    /**
     * Sets bins
     * @param \vmorc_100\model\Bins $bins
     * @return $this
     */
    public function setBins($bins)
    {
        $this->container['bins'] = $bins;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\vmorc_100\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\vmorc_100\ObjectSerializer::sanitizeForSerialization($this));
    }
}

/**
* ----------------------------------------------------------------------------------------------------------------------
*
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
* ----------------------------------------------------------------------------------------------------------------------
*/