

<p>Al aceptar este aviso de privacidad, usted da autorización del uso de sus datos en esta página con la siguiente finalidad. 
Basándose en lo estipulado dentro La Ley Federal De Protección de Datos en Posesión de los Particulares, COMERCIALIZADORA TIROC S A DE C V declara mantener el uso correcto a la información obtenida por medio del formulario contenido en la página oficial de nuestra empresa y redes sociales pertenecientes a la misma, con el objetivo de dar seguimiento a la solicitud de información del usuario e igualmente se permite brindar asesoría sobre nuestros productos y servicios.
COMERCIALIZADORA TIROC S A DE C V como parte de nuestras políticas de integridad, no hace llamadas en solicitud de pagos anticipados por un producto y/o servicio, sin un contrato previo y un trámite debidamente en norma, al igual que mantiene todos los derechos reservados para no compartir la información con terceros. El sitio <span style="color: #460932;font-weight:bold;" >www.labuenacopa.com</span> le recomienda no proporcionar su información a nadie, más allá de la compra o información solicitada. En todo momento el usuario es el responsable único y final de mantener en secreto sus datos personales.
Para el usuario
Si su forma de pago es con tarjeta bancaria, se le solicitarán los siguientes datos, los cuales en términos del artículo 8 de la Ley federal de protección de datos personales en posesión de los particulares, se consideran dentro de la categoría de datos personales financieros o patrimoniales: El nombre del titular de la tarjeta, el número de la tarjeta, la fecha de vencimiento de la tarjeta y el nombre del banco. La Ley pide que en caso de que los datos personales recopilados incluyan datos sensibles o patrimoniales y/o financieros, el Responsable lleve a cabo actos que recojan y constituyan el consentimiento expreso del titular como los dispone el segundo párrafo del artículo 8 de la Ley y demás legislaciones aplicables, bien, mediante la firma del formato correspondiente, sea impreso, o utilizando medios electrónicos, a través de respuestas directas, y sus correspondientes procesos para la formación del consentimiento, a título enunciativo mas no limitativo, mediante el consentimiento expreso y suministro por parte del Titular de datos personales. El consentimiento Tácito resulta de hechos o actos que lo presupongan. De tal forma que, ante la ausencia de su negativa, tomaremos en cuenta su consentimiento en esos términos. En términos de lo establecido en el artículo 9 de la Ley Federal de Protección a los Datos Personales en Posesión de los Particulares, se le solicita su consentimiento expreso para el tratamiento de los datos personales sensibles, financieros y patrimoniales, indicándonos si acepta o no el tratamiento. Recordando que en términos del artículo 1803 del Código Civil Federal, el consentimiento es expreso cuando se manifiesta verbalmente, por escrito o por signos inequívocos.
</p>
<p>Respecto a la empresa:
La empresa COMERCIALIZADORA TIROC SE DE CV se identifica como: COMERCIALIZADORA TIROC SE DE CV ubicado en AV insurgentes Norte 1319 int 202 col Guadalupe, Teléfono 5521240710, Correo atencion@labuenacopa.com 
Sin embargo, sus datos personales podrán ser utilizados en las actividades que implican:

<li>Identificar que el usuario es mayor de edad y tiene el debido cumplimiento para realizar compras con nosotros.</li>
<li>Enviar promociones, publicidad y beneficios.</li>
<li>Avisar sobre productos o servicios nuevos</li>
<li>Elaborar estudios de mercadotecnia, segmentación, calidad, estadística</li>
<li>Permitir conocer la ubicación de nuestras sucursales</li>

La presente política se podrá modificar a medida que actualicemos y se extiendan nuestros servicios. Consulte regularmente si existe alguna actualización a esta política. Usted acuerda que su aceptación del Aviso de privacidad posterior a su consentimiento original, así como el uso del sitio web de <span style="color: #460932;font-weight:bold;" >www.labuenacopa.com</span>o el uso continuo de nuestro servicio después de publicar un cambio a esta política implica que acepta dichos cambios y se obliga a respetarlos. Podrá acceder a la última versión de este Aviso de privacidad visitando nuestro sitio web y haciendo clic en “Aviso de privacidad” al pie de las páginas del sitio web de  www.labuenacopa.com
Usted puede acceder a sus datos personales que poseemos y a los detalles del tratamiento de los mismos, así como a rectificarlos en caso de ser inexactos o incompletos; cancelarlos cuando considere que sea necesario, estén siendo utilizados para finalidades ya no consentidas o haya finalizado la relación contractual o de servicio.
</p>
