<?php
/**
 * CardBenefitsInner
 *
 * PHP version 5
 *
 * @category Class
 * @package  vces_100
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visa Card Eligibility Service
 *
 * Visa Card Eligibility Service REST API
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace vces_100\model;

use \ArrayAccess;

/**
 * CardBenefitsInner Class Doc Comment
 *
 * @category    Class
 * @package     vces_100
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CardBenefitsInner implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'cardBenefits_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'card_enhance_type_code' => 'string',
        'benefit_desc' => 'string',
        'phone_number_details' => 'string',
        'benefit_name' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'card_enhance_type_code' => 'cardEnhanceTypeCode',
        'benefit_desc' => 'benefitDesc',
        'phone_number_details' => 'phoneNumberDetails',
        'benefit_name' => 'benefitName'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'card_enhance_type_code' => 'setCardEnhanceTypeCode',
        'benefit_desc' => 'setBenefitDesc',
        'phone_number_details' => 'setPhoneNumberDetails',
        'benefit_name' => 'setBenefitName'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'card_enhance_type_code' => 'getCardEnhanceTypeCode',
        'benefit_desc' => 'getBenefitDesc',
        'phone_number_details' => 'getPhoneNumberDetails',
        'benefit_name' => 'getBenefitName'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['card_enhance_type_code'] = isset($data['card_enhance_type_code']) ? $data['card_enhance_type_code'] : null;
        $this->container['benefit_desc'] = isset($data['benefit_desc']) ? $data['benefit_desc'] : null;
        $this->container['phone_number_details'] = isset($data['phone_number_details']) ? $data['phone_number_details'] : null;
        $this->container['benefit_name'] = isset($data['benefit_name']) ? $data['benefit_name'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['benefit_desc'] === null) {
            $invalid_properties[] = "'benefit_desc' can't be null";
        }
        if ($this->container['benefit_name'] === null) {
            $invalid_properties[] = "'benefit_name' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['benefit_desc'] === null) {
            return false;
        }
        if ($this->container['benefit_name'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets card_enhance_type_code
     * @return string
     */
    public function getCardEnhanceTypeCode()
    {
        return $this->container['card_enhance_type_code'];
    }

    /**
     * Sets card_enhance_type_code
     * @param string $card_enhance_type_code Maximum 10 UTF-8 bytes.
     * @return $this
     */
    public function setCardEnhanceTypeCode($card_enhance_type_code)
    {
        $this->container['card_enhance_type_code'] = $card_enhance_type_code;

        return $this;
    }

    /**
     * Gets benefit_desc
     * @return string
     */
    public function getBenefitDesc()
    {
        return $this->container['benefit_desc'];
    }

    /**
     * Sets benefit_desc
     * @param string $benefit_desc Decription of the benefit
     * @return $this
     */
    public function setBenefitDesc($benefit_desc)
    {
        $this->container['benefit_desc'] = $benefit_desc;

        return $this;
    }

    /**
     * Gets phone_number_details
     * @return string
     */
    public function getPhoneNumberDetails()
    {
        return $this->container['phone_number_details'];
    }

    /**
     * Sets phone_number_details
     * @param string $phone_number_details This object contains complete phone number data for a single telephone number.
     * @return $this
     */
    public function setPhoneNumberDetails($phone_number_details)
    {
        $this->container['phone_number_details'] = $phone_number_details;

        return $this;
    }

    /**
     * Gets benefit_name
     * @return string
     */
    public function getBenefitName()
    {
        return $this->container['benefit_name'];
    }

    /**
     * Sets benefit_name
     * @param string $benefit_name Benefit Name
     * @return $this
     */
    public function setBenefitName($benefit_name)
    {
        $this->container['benefit_name'] = $benefit_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\vces_100\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\vces_100\ObjectSerializer::sanitizeForSerialization($this));
    }
}

/**
* ----------------------------------------------------------------------------------------------------------------------
*
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
* ----------------------------------------------------------------------------------------------------------------------
*/