<?php
/**
 * ResponseValuesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ml_100
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Merchant Locator API
 *
 * Find Visa accepting merchants around by geolocation
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ml_100\modeltest;

/**
 * ResponseValuesTest Class Doc Comment
 *
 * @category    Class */
// * @description 
/**
 * @package     ml_100
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseValuesTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ResponseValues"
     */
    public function testResponseValues()
    {

    }

    /**
     * Test attribute "location_address_latitude"
     */
    public function testPropertyLocationAddressLatitude()
    {

    }

    /**
     * Test attribute "merchant_city"
     */
    public function testPropertyMerchantCity()
    {

    }

    /**
     * Test attribute "merchant_street_address"
     */
    public function testPropertyMerchantStreetAddress()
    {

    }

    /**
     * Test attribute "merchant_category_code"
     */
    public function testPropertyMerchantCategoryCode()
    {

    }

    /**
     * Test attribute "distance"
     */
    public function testPropertyDistance()
    {

    }

    /**
     * Test attribute "visa_enterprise_name"
     */
    public function testPropertyVisaEnterpriseName()
    {

    }

    /**
     * Test attribute "business_legal_name"
     */
    public function testPropertyBusinessLegalName()
    {

    }

    /**
     * Test attribute "visa_store_name"
     */
    public function testPropertyVisaStoreName()
    {

    }

    /**
     * Test attribute "visa_merchant_id"
     */
    public function testPropertyVisaMerchantId()
    {

    }

    /**
     * Test attribute "merchant_category_code_desc"
     */
    public function testPropertyMerchantCategoryCodeDesc()
    {

    }

    /**
     * Test attribute "merchant_state"
     */
    public function testPropertyMerchantState()
    {

    }

    /**
     * Test attribute "visa_merchant_name"
     */
    public function testPropertyVisaMerchantName()
    {

    }

    /**
     * Test attribute "merchant_country_code"
     */
    public function testPropertyMerchantCountryCode()
    {

    }

    /**
     * Test attribute "merchant_postal_code"
     */
    public function testPropertyMerchantPostalCode()
    {

    }

    /**
     * Test attribute "dbaname"
     */
    public function testPropertyDbaname()
    {

    }

    /**
     * Test attribute "visa_store_id"
     */
    public function testPropertyVisaStoreId()
    {

    }

    /**
     * Test attribute "payment_facilitator_name"
     */
    public function testPropertyPaymentFacilitatorName()
    {

    }

    /**
     * Test attribute "merchant_url"
     */
    public function testPropertyMerchantUrl()
    {

    }

    /**
     * Test attribute "location_address_longitude"
     */
    public function testPropertyLocationAddressLongitude()
    {

    }

}


/**
* --------------------------------------------------------------------------------
*
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
* --------------------------------------------------------------------------------
*/