<?php
/**
 * BatchEnrollmentpostPayload
 *
 * PHP version 5
 *
 * @category Class
 * @package  pmc_100
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Customer Rules API
 *
 * The Customer Rules API enables consumers to establish control rules that will define the type of transactions they want to Manage.
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace pmc_100\model;

use \ArrayAccess;

/**
 * BatchEnrollmentpostPayload Class Doc Comment
 *
 * @category    Class
 * @description request
 * @package     pmc_100
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BatchEnrollmentpostPayload implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'batchEnrollmentpostPayload';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'control_rules' => '\pmc_100\model\ControlRules',
        'cards_type' => 'string',
        'force_enrollment' => 'bool',
        'enrolled_cards' => '\pmc_100\model\EnrolledCards'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'control_rules' => 'controlRules',
        'cards_type' => 'cardsType',
        'force_enrollment' => 'forceEnrollment',
        'enrolled_cards' => 'enrolledCards'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'control_rules' => 'setControlRules',
        'cards_type' => 'setCardsType',
        'force_enrollment' => 'setForceEnrollment',
        'enrolled_cards' => 'setEnrolledCards'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'control_rules' => 'getControlRules',
        'cards_type' => 'getCardsType',
        'force_enrollment' => 'getForceEnrollment',
        'enrolled_cards' => 'getEnrolledCards'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['control_rules'] = isset($data['control_rules']) ? $data['control_rules'] : null;
        $this->container['cards_type'] = isset($data['cards_type']) ? $data['cards_type'] : null;
        $this->container['force_enrollment'] = isset($data['force_enrollment']) ? $data['force_enrollment'] : null;
        $this->container['enrolled_cards'] = isset($data['enrolled_cards']) ? $data['enrolled_cards'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['control_rules'] === null) {
            $invalid_properties[] = "'control_rules' can't be null";
        }
        if ($this->container['enrolled_cards'] === null) {
            $invalid_properties[] = "'enrolled_cards' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['control_rules'] === null) {
            return false;
        }
        if ($this->container['enrolled_cards'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets control_rules
     * @return \pmc_100\model\ControlRules
     */
    public function getControlRules()
    {
        return $this->container['control_rules'];
    }

    /**
     * Sets control_rules
     * @param \pmc_100\model\ControlRules $control_rules
     * @return $this
     */
    public function setControlRules($control_rules)
    {
        $this->container['control_rules'] = $control_rules;

        return $this;
    }

    /**
     * Gets cards_type
     * @return string
     */
    public function getCardsType()
    {
        return $this->container['cards_type'];
    }

    /**
     * Sets cards_type
     * @param string $cards_type This represents whether the list of accountIdentifier is PAN or TOKEN.
     * @return $this
     */
    public function setCardsType($cards_type)
    {
        $this->container['cards_type'] = $cards_type;

        return $this;
    }

    /**
     * Gets force_enrollment
     * @return bool
     */
    public function getForceEnrollment()
    {
        return $this->container['force_enrollment'];
    }

    /**
     * Sets force_enrollment
     * @param bool $force_enrollment If the indicator is set to true, previously enrolled accountIdentifier will be overwritten.
     * @return $this
     */
    public function setForceEnrollment($force_enrollment)
    {
        $this->container['force_enrollment'] = $force_enrollment;

        return $this;
    }

    /**
     * Gets enrolled_cards
     * @return \pmc_100\model\EnrolledCards
     */
    public function getEnrolledCards()
    {
        return $this->container['enrolled_cards'];
    }

    /**
     * Sets enrolled_cards
     * @param \pmc_100\model\EnrolledCards $enrolled_cards
     * @return $this
     */
    public function setEnrolledCards($enrolled_cards)
    {
        $this->container['enrolled_cards'] = $enrolled_cards;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\pmc_100\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\pmc_100\ObjectSerializer::sanitizeForSerialization($this));
    }
}

/**
* ----------------------------------------------------------------------------------------------------------------------
*
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
* ----------------------------------------------------------------------------------------------------------------------
*/