<?php
/**
 * PaymentsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  vpa_102
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Payment Service
 *
 * The Payment web service is used for processing payments and sending payment remittance information to the appropriate suppliers.
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace vpa_102\modeltest;

/**
 * PaymentsTest Class Doc Comment
 *
 * @category    Class */
// * @description This complex element contains the details of all the payments.
/**
 * @package     vpa_102
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Payments"
     */
    public function testPayments()
    {

    }

    /**
     * Test attribute "payment_gross_amount"
     */
    public function testPropertyPaymentGrossAmount()
    {

    }

    /**
     * Test attribute "payment_expiry_date"
     */
    public function testPropertyPaymentExpiryDate()
    {

    }

    /**
     * Test attribute "account_number"
     */
    public function testPropertyAccountNumber()
    {

    }

    /**
     * Test attribute "invoices"
     */
    public function testPropertyInvoices()
    {

    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {

    }

    /**
     * Test attribute "system_match_status"
     */
    public function testPropertySystemMatchStatus()
    {

    }

    /**
     * Test attribute "payment_description"
     */
    public function testPropertyPaymentDescription()
    {

    }

    /**
     * Test attribute "payment_request_date"
     */
    public function testPropertyPaymentRequestDate()
    {

    }

    /**
     * Test attribute "payment_type"
     */
    public function testPropertyPaymentType()
    {

    }

    /**
     * Test attribute "supplier"
     */
    public function testPropertySupplier()
    {

    }

    /**
     * Test attribute "manual_match_status"
     */
    public function testPropertyManualMatchStatus()
    {

    }

}


/**
* --------------------------------------------------------------------------------
*
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
* --------------------------------------------------------------------------------
*/