<?php
/**
 * ReportingApigetResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  rpt_100
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reports API
 *
 * The Reports API provides reporting capabilities such as transaction reconciliation data API. The data needed for reconciliation includes both push(OCT) and pull(AFT) transaction details and any exceptions such as chargebacks & reversals. This data allows you to reconcile the transactions sent by your systems with what was processed through VisaNet.<br> <br> <b>Note: This functionality is currently available for US transactions ONLY.</b>
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace rpt_100\modeltest;

/**
 * ReportingApigetResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description Transaction Data response
/**
 * @package     rpt_100
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReportingApigetResponseTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ReportingApigetResponse"
     */
    public function testReportingApigetResponse()
    {

    }

    /**
     * Test attribute "settlement_date_time"
     */
    public function testPropertySettlementDateTime()
    {

    }

    /**
     * Test attribute "approval_code"
     */
    public function testPropertyApprovalCode()
    {

    }

    /**
     * Test attribute "card_acceptor_id_code"
     */
    public function testPropertyCardAcceptorIdCode()
    {

    }

    /**
     * Test attribute "fee_program_indicator"
     */
    public function testPropertyFeeProgramIndicator()
    {

    }

    /**
     * Test attribute "fee_program_desc"
     */
    public function testPropertyFeeProgramDesc()
    {

    }

    /**
     * Test attribute "card_acceptor_name"
     */
    public function testPropertyCardAcceptorName()
    {

    }

    /**
     * Test attribute "transaction_currency_code"
     */
    public function testPropertyTransactionCurrencyCode()
    {

    }

    /**
     * Test attribute "transaction_identifier"
     */
    public function testPropertyTransactionIdentifier()
    {

    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {

    }

    /**
     * Test attribute "acquiring_bin"
     */
    public function testPropertyAcquiringBin()
    {

    }

    /**
     * Test attribute "retrieval_reference_number"
     */
    public function testPropertyRetrievalReferenceNumber()
    {

    }

    /**
     * Test attribute "systems_trace_audit_number"
     */
    public function testPropertySystemsTraceAuditNumber()
    {

    }

    /**
     * Test attribute "processing_date"
     */
    public function testPropertyProcessingDate()
    {

    }

    /**
     * Test attribute "account_number_masked"
     */
    public function testPropertyAccountNumberMasked()
    {

    }

    /**
     * Test attribute "reason_code"
     */
    public function testPropertyReasonCode()
    {

    }

    /**
     * Test attribute "transaction_date_time"
     */
    public function testPropertyTransactionDateTime()
    {

    }

    /**
     * Test attribute "transaction_state"
     */
    public function testPropertyTransactionState()
    {

    }

}


/**
* --------------------------------------------------------------------------------
*
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
* --------------------------------------------------------------------------------
*/