<?php
/**
 * ForeignexchangelookuppostResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  fx_100
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Foreign Exchange Rates API
 *
 * The Foreign Exchange Rates API provides an easy access to the Visa daily currency conversion rate for a given currency pair.  This is an indicative rate which is dependent on the currency pair as well as the amount, and may be different from the actual rate for settlement of transaction.
 *
 * OpenAPI spec version: v1
 * Contact: 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace fx_100\modeltest;

/**
 * ForeignexchangelookuppostResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description 
/**
 * @package     fx_100
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ForeignexchangelookuppostResponseTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ForeignexchangelookuppostResponse"
     */
    public function testForeignexchangelookuppostResponse()
    {

    }

    /**
     * Test attribute "conversion_rate"
     */
    public function testPropertyConversionRate()
    {

    }

    /**
     * Test attribute "original_destn_amt_before_mark_up"
     */
    public function testPropertyOriginalDestnAmtBeforeMarkUp()
    {

    }

    /**
     * Test attribute "mark_up_rate_applied"
     */
    public function testPropertyMarkUpRateApplied()
    {

    }

    /**
     * Test attribute "destination_amount"
     */
    public function testPropertyDestinationAmount()
    {

    }

}


/**
* --------------------------------------------------------------------------------
*
* © Copyright 2018 Visa. All Rights Reserved.
*
* NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
* and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
* rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
*
* By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
* (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
* programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
* THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
* FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
* --------------------------------------------------------------------------------
*/